///////////////////////////////////////////////////////////
//  WeChatMember.cs
//  Implementation of the Class WeChatMember
//  Generated by Enterprise Architect
//  Created on:      09-12月-2017 11:44:03
//  Original author: Huachao
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace Diego.WxHttpSdk
{
	/// <summary>
	/// 微信成员,一个对应一个微信好友
	/// </summary>
	public class WeChatMember {

		/// <summary>
		/// 别名
		/// </summary>
		private string _alias;
		/// <summary>
		/// 不知道干什么的
		/// </summary>
		private int _appAccountFlag;
		private long _attrStatus;
		private int _chatRoomId;
		/// <summary>
		/// 市
		/// </summary>
		private string _city;
		/// <summary>
		/// 区分好友类型
		/// 值为1是好友，值为2是群组,值为3是公众号
		/// </summary>
		private int _contactFlag;
		private string _displayName;
		/// <summary>
		/// 头像链接地址
		/// </summary>
		private string _headImgUrl;
		private int _hideInputBarFlag;
		private int _isOwner;
		private string _keyWord;
		/// <summary>
		/// 成员数量,只有在群组的时候才有效
		/// </summary>
		private int _memberCount;
		/// <summary>
		/// 群组成员列表
		/// </summary>
		private WeChatMember[] _memberList;
		/// <summary>
		/// 昵称
		/// </summary>
		private string _nickName;
		private int _ownerUin;
		/// <summary>
		/// 省
		/// </summary>
		private string _province;
		/// <summary>
		/// 用户拼音的缩写
		/// </summary>
		private string _pYInitial;
		/// <summary>
		/// 用户拼音的全拼
		/// </summary>
		private string _pYQuanPin;
		/// <summary>
		/// 备注名称
		/// </summary>
		private string _remarkName;
		/// <summary>
		/// 备注拼音缩写
		/// </summary>
		private string _remarkPYInitial;
		/// <summary>
		/// 备注拼音全拼
		/// </summary>
		private string _remarkPYQuanPin;
		/// <summary>
		/// 性别，0-未设置（公众号、保密），1-男，2-女
		/// </summary>
		private int _sex;
		/// <summary>
		/// 公众号的功能介绍 or 好友的个性签名
		/// </summary>
		private string _signature;
		private int _snsFlag;
		/// <summary>
		/// 是否为星标朋友  0-否  1-是
		/// </summary>
		private int _starFriend;
		private int _statues;
		private int _uin;
		private int _uniFriend;
		/// <summary>
		/// 用户名称，一个"
		/// </summary>
		private string _userName;
		private int _verifyFlag;


		/// <summary>
		/// 别名
		/// </summary>
		public string Alias{
			get{
				return _alias;
			}
			set{
				_alias = value;
			}
		}

		/// <summary>
		/// 不知道干什么的
		/// </summary>
		public int AppAccountFlag{
			get{
				return _appAccountFlag;
			}
			set{
				_appAccountFlag = value;
			}
		}

		public long AttrStatus{
			get{
				return _attrStatus;
			}
			set{
				_attrStatus = value;
			}
		}

		public int ChatRoomId{
			get{
				return _chatRoomId;
			}
			set{
				_chatRoomId = value;
			}
		}

		/// <summary>
		/// 市
		/// </summary>
		public string City{
			get{
				return _city;
			}
			set{
				_city = value;
			}
		}

		/// <summary>
		/// 区分好友类型
		/// 值为1是好友，值为2是群组,值为3是公众号
		/// </summary>
		public int ContactFlag{
			get{
				return _contactFlag;
			}
			set{
				_contactFlag = value;
			}
		}

		public string DisplayName{
			get{
				return _displayName;
			}
			set{
				_displayName = value;
			}
		}

		/// <summary>
		/// 头像链接地址
		/// </summary>
		public string HeadImgUrl{
			get{
				return _headImgUrl;
			}
			set{
				_headImgUrl = value;
			}
		}

		public int HideInputBarFlag{
			get{
				return _hideInputBarFlag;
			}
			set{
				_hideInputBarFlag = value;
			}
		}

		public int IsOwner{
			get{
				return _isOwner;
			}
			set{
				_isOwner = value;
			}
		}

		public string KeyWord{
			get{
				return _keyWord;
			}
			set{
				_keyWord = value;
			}
		}

		/// <summary>
		/// 成员数量,只有在群组的时候才有效
		/// </summary>
		public int MemberCount{
			get{
				return _memberCount;
			}
			set{
				_memberCount = value;
			}
		}

		/// <summary>
		/// 群组成员列表
		/// </summary>
		public WeChatMember[] MemberList{
			get{
				return _memberList;
			}
			set{
				_memberList = value;
			}
		}

		/// <summary>
		/// 昵称
		/// </summary>
		public string NickName{
			get{
				return _nickName;
			}
			set{
				_nickName = value;
			}
		}

		public int OwnerUin{
			get{
				return _ownerUin;
			}
			set{
				_ownerUin = value;
			}
		}

		/// <summary>
		/// 省
		/// </summary>
		public string Province{
			get{
				return _province;
			}
			set{
				_province = value;
			}
		}

		/// <summary>
		/// 用户拼音的缩写
		/// </summary>
		public string PYInitial{
			get{
				return _pYInitial;
			}
			set{
				_pYInitial = value;
			}
		}

		/// <summary>
		/// 用户拼音的全拼
		/// </summary>
		public string PYQuanPin{
			get{
				return _pYQuanPin;
			}
			set{
				_pYQuanPin = value;
			}
		}

		/// <summary>
		/// 备注名称
		/// </summary>
		public string RemarkName{
			get{
				return _remarkName;
			}
			set{
				_remarkName = value;
			}
		}

		/// <summary>
		/// 备注拼音缩写
		/// </summary>
		public string RemarkPYInitial{
			get{
				return _remarkPYInitial;
			}
			set{
				_remarkPYInitial = value;
			}
		}

		/// <summary>
		/// 备注拼音全拼
		/// </summary>
		public string RemarkPYQuanPin{
			get{
				return _remarkPYQuanPin;
			}
			set{
				_remarkPYQuanPin = value;
			}
		}

		/// <summary>
		/// 性别，0-未设置（公众号、保密），1-男，2-女
		/// </summary>
		public int Sex{
			get{
				return _sex;
			}
			set{
				_sex = value;
			}
		}

		/// <summary>
		/// 公众号的功能介绍 or 好友的个性签名
		/// </summary>
		public string Signature{
			get{
				return _signature;
			}
			set{
				_signature = value;
			}
		}

		public int SnsFlag{
			get{
				return _snsFlag;
			}
			set{
				_snsFlag = value;
			}
		}

		/// <summary>
		/// 是否为星标朋友  0-否  1-是
		/// </summary>
		public int StarFriend{
			get{
				return _starFriend;
			}
			set{
				_starFriend = value;
			}
		}

		public int Statues{
			get{
				return _statues;
			}
			set{
				_statues = value;
			}
		}

		public int Uin{
			get{
				return _uin;
			}
			set{
				_uin = value;
			}
		}

		public int UniFriend{
			get{
				return _uniFriend;
			}
			set{
				_uniFriend = value;
			}
		}

		/// <summary>
		/// 用户名称，一个"
		/// </summary>
		public string UserName{
			get{
				return _userName;
			}
			set{
				_userName = value;
			}
		}

		public int VerifyFlag{
			get{
				return _verifyFlag;
			}
			set{
				_verifyFlag = value;
			}
		}

        public string GetSex() {
            switch (this.Sex)
            {
                case 1:
                    return "男";
                case 2:
                    return "女";
            }
            return "保密";
        }

	}//end WeChatMember

}//end namespace Sdk